Repository octoposprime/op-infra, pull requests merged in 2024-03, with the labels that each got.

#9 Redis and Redisinsight YAML files added
  configYaml/redisConfig/redis.yaml
  configYaml/redisConfig/redisinsight.yaml
Labels: DevOps

#10 Postgres and PGadmin YAML files added
  configYaml/pgConfig/pgadmin.yaml
  configYaml/pgConfig/postgres.yaml
Labels: DevOps

#12 Added Dev Env for k8s
  README.md
  dev/postgresql/pgadmin.yaml
  dev/postgresql/postgres.yaml
  dev/redis/redis.yaml
  dev/redis/redisinsight.yaml
  dev/service/graphql.yml
  dev/service/logging.yml
  dev/service/user.yml
Labels: documentation, DevOps

#14 Update redis.yaml
  dev/redis/redis.yaml
Labels: bug
